..........FF.FF.
======================================================================
FAIL: test_11 (__main__.UnicodeTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "UnicodeTests.py", line 73, in test_11
    self.assertEqual('i'.upper(), 'İ')
AssertionError: 'I' != 'İ'
- I
+ İ


======================================================================
FAIL: test_12 (__main__.UnicodeTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "UnicodeTests.py", line 77, in test_12
    self.assertEqual('I'.lower(), 'ı')
AssertionError: 'i' != 'ı'
- i
+ ı


======================================================================
FAIL: test_14 (__main__.UnicodeTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "UnicodeTests.py", line 84, in test_14
    self.assertEqual(len('\u30C8\u3099'), 1)
AssertionError: 2 != 1

======================================================================
FAIL: test_15 (__main__.UnicodeTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "UnicodeTests.py", line 88, in test_15
    self.assertEqual(len('e\u3081\U0001D11E\u30C8\u3099'), 3)
AssertionError: 5 != 3

----------------------------------------------------------------------
Ran 16 tests in 0.001s

FAILED (failures=4)
